swagger: "2.0"
info:
  version: "0.0.2"
  title: Tegan Straley Web API assignment 2
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /posts:
    # binds swagger app logic to a route
    x-swagger-router-controller: Node
    post:
      description: posts for post
      # used as the method name of the controller
      operationId: posts
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
            
            
  /puts:
    # binds swagger app logic to a route
    x-swagger-router-controller: Node
    put:
      description: puts for put
      # used as the method name of the controller
      operationId: put
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /deletes:
    # binds swagger app logic to a route
    x-swagger-router-controller: Node
    delete:
      description: deletes for delete
      # used as the method name of the controller
      operationId: deleteFunction
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /gets:
    # binds swagger app logic to a route
    x-swagger-router-controller: Node
    get:
      description: gets for get
      # used as the method name of the controller
      operationId: get
      responses:
        "200":
          description: Success
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
    
    
    
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
